[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_PATHS = "EMAIL_SETUP_README.md,ENV_SETUP.md,.env.example,src/components/*,src/pages/*,*.md"
  SECRETS_SCAN_OMIT_KEYS = "contact@vishalcreations.com,info@vishalcreations.com,admin@vishalcreations.com"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
